# Generated by Django 3.0.5 on 2020-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Alive?'),
        ),
    ]
