# Generated by Django 3.0.5 on 2020-07-03 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_plant_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='current_location',
            field=models.TextField(blank=True, default='', verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='genus',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Genus'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='monicker',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Monicker'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Plant Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Species'),
        ),
    ]
