# Generated by Django 3.0.5 on 2020-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200703_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pheno_compat',
            field=models.BooleanField(default=True, verbose_name='Self incompatible'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_cyanogenic_enzyme',
            field=models.BooleanField(default=False, verbose_name='Linamarase (Li)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_cyanogenic_gluc',
            field=models.BooleanField(default=False, verbose_name='Cyanogenic Glucosides (Ac)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_flower_blush',
            field=models.BooleanField(default=False, verbose_name='Blush Flower'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_flower_morphology',
            field=models.BooleanField(default=True, verbose_name='Generic'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_flower_pink',
            field=models.BooleanField(default=False, verbose_name='Pink Flower'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_flower_red',
            field=models.BooleanField(default=False, verbose_name='Red Flower'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_flower_white',
            field=models.BooleanField(default=False, verbose_name='White Flower'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_basal',
            field=models.BooleanField(default=False, verbose_name='Basal (VL)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_brokenV',
            field=models.BooleanField(default=False, verbose_name='Broken V (Vb)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_brokenVyel',
            field=models.BooleanField(default=False, verbose_name='Broken V yellow tip (Vby)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_filledV',
            field=models.BooleanField(default=False, verbose_name='Filled V (Vf/_)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_halo',
            field=models.BooleanField(default=False, verbose_name='Halo (Vh2)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_marginalMark',
            field=models.BooleanField(default=False, verbose_name='Marginal Mark (Vm)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_multifoliate',
            field=models.BooleanField(default=False, verbose_name='Multifoliate'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_palmate',
            field=models.BooleanField(default=False, verbose_name='Palmate leaf'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_pinnate',
            field=models.BooleanField(default=False, verbose_name='Pinnate leaf'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_recessive',
            field=models.BooleanField(default=False, verbose_name='Green Leaf (vv)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_red',
            field=models.BooleanField(default=False, verbose_name='Red leaf (Rl)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_redFleck',
            field=models.BooleanField(default=False, verbose_name='Red Fleck (Rf)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_redLeaflet',
            field=models.BooleanField(default=False, verbose_name='Red leaflet (Vrl)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_redMidrib',
            field=models.BooleanField(default=False, verbose_name='Red Midrib (Rm)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_redSpot',
            field=models.BooleanField(default=False, verbose_name='Red Spot (Vr2)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_trifoliate',
            field=models.BooleanField(default=False, verbose_name='Trifoliate'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_vPoint',
            field=models.BooleanField(default=False, verbose_name='V Point (Vp)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_whiteV',
            field=models.BooleanField(default=False, verbose_name='White V (V/_)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_whiteVHigh',
            field=models.BooleanField(default=False, verbose_name='White V High (Vh/_)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_whiteVIntermediate',
            field=models.BooleanField(default=False, verbose_name='White V Intermediate (Vi/_)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pheno_leaf_whiteVLow',
            field=models.BooleanField(default=False, verbose_name='White V Low (Vl/_)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Current Location'),
        ),
    ]
